# QoL
set -g history-limit 50000
set -g allow-rename off
set -g mouse on

## Join windows
bind-key j command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"

# Search mode VI (default is emacs)
set-window-option -g mode-keys vi

# Set logging path
#set -g @logging-path "/home/david.rebelo/Documents/tmux-logs"

# Restoring pane contents
set -g @resurrect-capture-pane-contents 'on'

# Prefix Highlight
set -g status-right '#{prefix_highlight}'
set -g @prefix_highlight_show_copy_mode 'on'

# List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

## Theme
#set -g @plugin 'nordtheme/tmux'
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#FFFFFF"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str " kali "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# expanded icon (fullscreen icon)
#set -g @minimal-tmux-expanded-icon "󰊓 "

# on all tabs (default is false)
# false will make it visible for the current tab only
#set -g @minimal-tmux-show-expanded-icons-for-all-tabs true

# To add or remove extra text in status bar
#set -g @minimal-tmux-status-right-extra "  "
#set -g @minimal-tmux-status-left-extra ""

# To make the selection box rounded () or edged <>
# Default is nothing, when set to true default is edged
#set -g @minimal-tmux-use-arrow true
#set -g @minimal-tmux-right-arrow ""
#set -g @minimal-tmux-left-arrow ""

# If getting strings cut in left status or right
# Here 20 is the length of the characters in the string
#set -g status-right-length 20
#set -g status-left-length 20

# Initialize TMUX plugin manager (keep at bottom)
run -b '~/.tmux/plugins/tpm/tpm'
